In [1]:
import pandas as pd
import numpy as np

In [5]:
df =pd.read_csv("Housing.csv")
df =df.select_dtypes(include=[np.number])
df.head()

   LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60

In [6]:
max_abs = np.max(np.abs(df), axis=0)

scaled_df = df / max_abs

scaled_df.head()

    LotArea  MSSubClass
0  0.039258    0.315789
1  0.044600    0.105263
2  0.052266    0.315789
3  0.044368    0.368421
4  0.066250    0.315789

In [11]:
import pandas as pd
import zipfile

with zipfile.ZipFile("iris.zip") as z:
    with z.open("iris.data") as f:
        df = pd.read_csv(f, header=None)

# print(df.head())

# df = pd.read_csv("iris.zip", compression="zip")

print(df.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa